#!/usr/bin/env bash
# Install the KEYRING shim for a CLI binary (per-binary universal mode).
#
# After install, the binary at <bin-path> is a small shell wrapper that:
#   1. forces HTTPS_PROXY=http://127.0.0.1:<proxy-port>  (so traffic enters KEYRING)
#   2. drops to the 'keyring-jail' uid via `sudo -u`     (so pf rules constrain its egress)
#   3. execs the original binary, now at <bin-path>.keyring-real
#
# The real binary is chmod 750 root:keyring-jail, so direct invocation by non-jail
# users is refused at the filesystem layer. A NOPASSWD sudoers entry lets the calling
# user invoke it via the shim without typing a password.
#
# Usage (printed by `keyring gate install --name <cli>`):
#   sudo KEYRING_STATE=/path/to/.keyring-state.json bash jail/install-shim.sh <cli> <bin-path> <proxy-port>

set -u
[[ $EUID -eq 0 ]] || { echo "must run as root: sudo bash $0 $*"; exit 2; }
[[ "$(uname)" == "Darwin" ]] || { echo "macOS only"; exit 2; }

CLI_NAME="${1:?usage: $0 <cli-name> <bin-path> <proxy-port>}"
BIN_PATH="${2:?bin path required}"
PROXY_PORT="${3:-8080}"
JAIL_USER="${KEYRING_JAIL_USER:-keyring-jail}"
JAIL_GROUP="${KEYRING_JAIL_GROUP:-keyring-jail}"
INVOKING_USER="${SUDO_USER:-$USER}"
REAL_PATH="${BIN_PATH}.keyring-real"
SUDOERS_FILE="/etc/sudoers.d/keyring-shim-${CLI_NAME}"

# --- safety checks ---
[[ -e "$BIN_PATH" ]] || { echo "binary not found: $BIN_PATH"; exit 1; }
[[ -e "$REAL_PATH" ]] && { echo "already shimmed ($REAL_PATH exists). uninstall first: sudo bash jail/uninstall-shim.sh $CLI_NAME $BIN_PATH"; exit 1; }
id "$JAIL_USER" >/dev/null 2>&1 || { echo "jail user '$JAIL_USER' missing. run: sudo bash jail/jail-macos.sh init"; exit 1; }
# refuse to shim things that already look like shell scripts pointing to a real
if head -1 "$BIN_PATH" 2>/dev/null | grep -q "KEYRING shim"; then
  echo "$BIN_PATH already looks like a KEYRING shim. aborting to avoid double-wrap."; exit 1
fi

# --- 1. move real binary aside, restrict perms ---
mv "$BIN_PATH" "$REAL_PATH"
chown "root:$JAIL_GROUP" "$REAL_PATH"
chmod 750 "$REAL_PATH"
echo "  moved binary: $BIN_PATH → $REAL_PATH (perms 750 root:$JAIL_GROUP)"

# --- 2. write the shim ---
cat > "$BIN_PATH" <<EOF
#!/bin/sh
# KEYRING shim for $CLI_NAME — forces egress through the KEYRING proxy and into the jail uid.
# Installed by jail/install-shim.sh. To remove: sudo bash jail/uninstall-shim.sh $CLI_NAME $BIN_PATH
exec sudo -E -n -u $JAIL_USER \\
  HTTPS_PROXY="http://127.0.0.1:$PROXY_PORT" \\
  HTTP_PROXY="http://127.0.0.1:$PROXY_PORT" \\
  NO_PROXY="localhost,127.0.0.1,::1" \\
  KEYRING_CLI="$CLI_NAME" \\
  KEYRING_PROXIED=1 \\
  "$REAL_PATH" "\$@"
EOF
chown root:wheel "$BIN_PATH"
chmod 755 "$BIN_PATH"
echo "  installed shim: $BIN_PATH (perms 755 root:wheel)"

# --- 3. sudoers rule (NOPASSWD, narrowly scoped to this real binary, for the invoking user) ---
TMP_SUDOERS=$(mktemp)
cat > "$TMP_SUDOERS" <<EOF
# Generated by KEYRING jail/install-shim.sh. Allows '$INVOKING_USER' to run the
# real binary at $REAL_PATH as the jailed '$JAIL_USER' without a password prompt.
# Remove via: sudo bash jail/uninstall-shim.sh $CLI_NAME $BIN_PATH
$INVOKING_USER ALL=($JAIL_USER) NOPASSWD: $REAL_PATH
EOF
chmod 440 "$TMP_SUDOERS"
if ! visudo -c -f "$TMP_SUDOERS" >/dev/null; then
  echo "ERROR: sudoers validation failed. rolling back."
  rm -f "$TMP_SUDOERS"
  mv "$REAL_PATH" "$BIN_PATH"
  exit 1
fi
mv "$TMP_SUDOERS" "$SUDOERS_FILE"
echo "  installed sudoers entry: $SUDOERS_FILE"

# --- 4. update KEYRING state (best-effort; non-fatal if state file unwritable) ---
STATE="${KEYRING_STATE:-$(cd "$(dirname "$0")/.." && pwd)/.keyring-state.json}"
if [[ -f "$STATE" ]]; then
  node -e "
    const fs=require('fs');
    const p='$STATE';
    const s=JSON.parse(fs.readFileSync(p,'utf8'));
    s.gatedClis = s.gatedClis || {};
    s.gatedClis['$CLI_NAME'] = s.gatedClis['$CLI_NAME'] || { name: '$CLI_NAME' };
    Object.assign(s.gatedClis['$CLI_NAME'], { binPath: '$BIN_PATH', realPath: '$REAL_PATH', enforcement: 'shimmed', shimmedAt: Date.now() });
    fs.writeFileSync(p, JSON.stringify(s, null, 2));
  " 2>/dev/null && echo "  state updated: $STATE (enforcement=shimmed)" || echo "  (note: could not update state file at $STATE — run 'keyring gate add --name $CLI_NAME --bin $BIN_PATH' manually)"
fi

echo
echo "✅ $CLI_NAME is now gated."
echo
echo "verify:"
echo "  head -3 $BIN_PATH                                # confirm it's the KEYRING shim"
echo "  ls -l $BIN_PATH $REAL_PATH                       # shim is 755 root:wheel; real is 750 root:$JAIL_GROUP"
echo "  $CLI_NAME --help                                 # should still work, but routes via KEYRING"
echo "  sudo -u $JAIL_USER curl https://example.com      # should be REFUSED if jail-macos.sh is up"
