#!/usr/bin/env bash
# KEYRING macOS network jail: a dedicated 'keyring-jail' user whose only outbound
# permitted egress is loopback to the KEYRING proxy (and DNS). Enforced by pf.
#
#   sudo bash jail/jail-macos.sh init     # one-time: create user + group + anchor stub
#   sudo bash jail/jail-macos.sh up       # load deny-by-default pf rules
#   sudo bash jail/jail-macos.sh down     # unload rules (user/group remain)
#   sudo bash jail/jail-macos.sh status   # show current rules
#
# Then run an agent or shimmed CLI:
#   sudo -u keyring-jail HTTPS_PROXY=http://127.0.0.1:8080 HTTP_PROXY=http://127.0.0.1:8080 <cmd>
#
# IMPORTANT: run `sudo bash jail/verify-pf-user.sh` FIRST to confirm uid filtering
# actually works on this macOS version. If verify fails, this jail is honor-system.
set -u
[[ $EUID -eq 0 ]] || { echo "must run as root: sudo bash $0 $*"; exit 2; }
[[ "$(uname)" == "Darwin" ]] || { echo "macOS only — use jail.sh on Linux"; exit 2; }

JAIL_USER="${KEYRING_JAIL_USER:-keyring-jail}"
JAIL_GROUP="${KEYRING_JAIL_GROUP:-keyring-jail}"
PROXY_PORT="${KEYRING_PROXY_PORT:-8080}"
ANCHOR_NAME="keyring"
ANCHOR_FILE="/etc/pf.anchors/$ANCHOR_NAME"
CONF_FILE="/etc/pf.$ANCHOR_NAME.conf"

action="${1:-status}"

ensure_user() {
  if id "$JAIL_USER" >/dev/null 2>&1; then
    return 0
  fi
  echo "creating user '$JAIL_USER'..."
  local next_uid new_uid next_gid new_gid
  next_uid=$(dscl . -list /Users UniqueID | awk '{print $2}' | sort -n | tail -1)
  new_uid=$(( next_uid + 1 ))
  next_gid=$(dscl . -list /Groups PrimaryGroupID | awk '{print $2}' | sort -n | tail -1)
  new_gid=$(( next_gid + 1 ))

  dscl . -create "/Groups/$JAIL_GROUP"
  dscl . -create "/Groups/$JAIL_GROUP" PrimaryGroupID "$new_gid"
  dscl . -create "/Groups/$JAIL_GROUP" RealName "KEYRING jailed processes"

  dscl . -create "/Users/$JAIL_USER"
  dscl . -create "/Users/$JAIL_USER" UserShell /bin/sh
  dscl . -create "/Users/$JAIL_USER" RealName "KEYRING jail"
  dscl . -create "/Users/$JAIL_USER" UniqueID "$new_uid"
  dscl . -create "/Users/$JAIL_USER" PrimaryGroupID "$new_gid"
  dscl . -create "/Users/$JAIL_USER" NFSHomeDirectory /var/empty
  echo "  uid=$new_uid gid=$new_gid"
}

write_anchor() {
  local uid gid
  uid=$(id -u "$JAIL_USER")
  gid=$(id -g "$JAIL_USER")
  cat > "$ANCHOR_FILE" <<EOF
# KEYRING jail — default-deny egress for uid $uid ($JAIL_USER), except:
#   - loopback to the KEYRING proxy (TCP $PROXY_PORT)
#   - DNS (UDP/TCP 53)
# Generated by jail-macos.sh. Do not edit by hand.

# allow loopback to the proxy
pass out quick proto tcp from any to 127.0.0.1 port $PROXY_PORT user $uid keep state
pass out quick proto tcp from any to ::1 port $PROXY_PORT user $uid keep state

# allow DNS (so the agent can resolve the proxy + so the proxy can resolve dests it tunnels to)
pass out quick proto udp from any to any port 53 user $uid keep state
pass out quick proto tcp from any to any port 53 user $uid keep state

# drop everything else for the jailed uid
block drop out quick proto tcp from any to any user $uid
block drop out quick proto udp from any to any user $uid
EOF
  cat > "$CONF_FILE" <<EOF
# KEYRING jail loader — installed by jail-macos.sh
anchor "$ANCHOR_NAME"
load anchor "$ANCHOR_NAME" from "$ANCHOR_FILE"
EOF
}

case "$action" in
  init)
    mkdir -p /etc/pf.anchors
    ensure_user
    write_anchor
    echo "jail initialized."
    echo "  user/group: $JAIL_USER"
    echo "  anchor:     $ANCHOR_FILE"
    echo "  loader:     $CONF_FILE"
    echo
    echo "next: sudo bash $0 up"
    ;;
  up)
    if ! id "$JAIL_USER" >/dev/null 2>&1; then
      echo "user '$JAIL_USER' missing — run 'sudo bash $0 init' first."
      exit 1
    fi
    write_anchor   # always refresh in case PROXY_PORT changed
    pfctl -f "$CONF_FILE"
    pfctl -E 2>&1 | grep -v "already enabled" || true
    echo
    echo "loaded rules for anchor '$ANCHOR_NAME':"
    pfctl -a "$ANCHOR_NAME" -s rules 2>/dev/null | sed 's/^/  /'
    echo
    echo "test:  sudo -u $JAIL_USER curl -s -o /dev/null -w '%{http_code}\\n' https://example.com   # expect 000 (refused)"
    ;;
  down)
    pfctl -a "$ANCHOR_NAME" -F all 2>/dev/null || true
    pfctl -f /etc/pf.conf 2>/dev/null || true
    echo "jail rules removed (user/group remain)."
    echo "to remove the user too:"
    echo "  sudo dscl . -delete /Users/$JAIL_USER"
    echo "  sudo dscl . -delete /Groups/$JAIL_GROUP"
    ;;
  status)
    if id "$JAIL_USER" >/dev/null 2>&1; then
      uid=$(id -u "$JAIL_USER")
      echo "user:   $JAIL_USER (uid=$uid)  ✓"
    else
      echo "user:   $JAIL_USER  ✗ (run: sudo bash $0 init)"
    fi
    if [[ -f "$ANCHOR_FILE" ]]; then
      echo "anchor: $ANCHOR_FILE  ✓"
    else
      echo "anchor: $ANCHOR_FILE  ✗"
    fi
    echo
    echo "active rules in anchor '$ANCHOR_NAME':"
    pfctl -a "$ANCHOR_NAME" -s rules 2>/dev/null | sed 's/^/  /' || echo "  (none / pf not loaded)"
    ;;
  *)
    echo "usage: sudo bash $0 init|up|down|status"
    echo "env:   KEYRING_JAIL_USER=$JAIL_USER  KEYRING_PROXY_PORT=$PROXY_PORT"
    exit 1
    ;;
esac
